=begin
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


start with 3 as the term and 2 as the first number to add

PROGRAM Fibonacci {

while term is less than 4M
  check if term is even
    if it is
      add it to the array
    if not
      do nothing
    end
    increment the term by adding the previous number to it
    the previous number is now the term
  end
}
=end


num1 = 1
num2 = 2
new_array = Array.new

term = 0

while term < 4000000
  if term % 2 == 0 
    new_array << term
  end
  term = num1 + num2 
  num1 = num2
  num2 = term
end

grand_total = new_array.inject(0) { |r, e| r + e }    
puts "The total of all even numbers is: #{grand_total}"





